#!/bin/bash

# Check if the script is being run as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Check if a username was provided as an argument
if [[ $# -eq 0 ]]; then
   echo "No username provided"
   exit 1
fi

# Run the whoami command as the specified user
sudo -u $1 whoami
